import { Song } from '@/types/song';

export const PRESET_SONGS: Song[] = [
  {
    id: 'u-ia-hoe',
    title: '雨夜花 (Ú-iā-hoe)',
    subtitle: '周添旺 詞 / 鄧雨賢 曲 (信望愛白話字 POJ 對齊·全四段)',
    composer: '鄧雨賢 (Tēng Ú-hiân)',
    lyricist: '周添旺 (Chiu Thiam-ōng)',
    key: 'Bb',
    timeSignature: '4/4',
    bpm: 72,
    notesPerLine: 2,
    description: '經典臺灣歌謠《雨夜花》，降B調 (4/4拍)，完整收錄白話字 (POJ) 與漢羅字字對齊之全四段（共32小節）。時值倍增且適時換行，短句好讀好唱。',
    measures: [
      // ======================================================================
      // VERSE 1 (Measures 1 - 8)
      // ======================================================================
      {
        id: 'u_m1',
        measureNumber: 1,
        chord: 'Bb',
        section: 'Verse 1',
        notes: [
          { id: 'u_v1_n1', pitch: 5, octave: -1, duration: 0.5, slurToNext: true, lyric: { poj: 'Ú', hanlo: '雨' } },
          { id: 'u_v1_n2', pitch: 6, octave: -1, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v1_n3', pitch: 5, octave: -1, duration: 1.0, lyric: { poj: 'iā', hanlo: '夜' } },
          { id: 'u_v1_n4', pitch: 3, octave: 0, duration: 2.0, lyric: { poj: 'hoe', hanlo: '花' } },
        ],
      },
      {
        id: 'u_m2',
        measureNumber: 2,
        chord: 'Gm',
        isLineBreak: true,
        notes: [
          { id: 'u_v1_n5', pitch: 3, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'ú', hanlo: '雨' } },
          { id: 'u_v1_n6', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v1_n7', pitch: 1, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'iā', hanlo: '夜' } },
          { id: 'u_v1_n8', pitch: 6, octave: -1, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v1_n9', pitch: 5, octave: -1, duration: 2.0, lyric: { poj: 'hoe', hanlo: '花' } },
          { id: 'u_v1_b1', pitch: 'empty', octave: 0, duration: 0, lyric: { poj: '\n', hanlo: '\n', hanji: '\n', custom: '\n' } },
        ],
      },
      {
        id: 'u_m3',
        measureNumber: 3,
        chord: 'Eb',
        notes: [
          { id: 'u_v1_n10', pitch: 1, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'siū', hanlo: '受' } },
          { id: 'u_v1_n11', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v1_n12', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'hong', hanlo: '風' } },
          { id: 'u_v1_n13', pitch: 5, octave: 0, duration: 1.0, lyric: { poj: 'hō͘', hanlo: '雨' } },
          { id: 'u_v1_n14', pitch: 1, octave: 1, duration: 0.5, slurToNext: true, annotation: '過門', lyric: { poj: '', hanlo: '' } },
          { id: 'u_v1_n15', pitch: 2, octave: 1, duration: 0.5, lyric: { poj: '', hanlo: '' } },
        ],
      },
      {
        id: 'u_m4',
        measureNumber: 4,
        chord: 'F7',
        isLineBreak: true,
        notes: [
          { id: 'u_v1_n16', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'chhoe', hanlo: '吹' } },
          { id: 'u_v1_n17', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'lo̍h', hanlo: '落' } },
          { id: 'u_v1_n18', pitch: 2, octave: 0, duration: 2.0, lyric: { poj: 'tē', hanlo: '地' } },
          { id: 'u_v1_b2', pitch: 'empty', octave: 0, duration: 0, lyric: { poj: '\n', hanlo: '\n', hanji: '\n', custom: '\n' } },
        ],
      },
      {
        id: 'u_m5',
        measureNumber: 5,
        chord: 'Bb',
        notes: [
          { id: 'u_v1_n19', pitch: 5, octave: 0, duration: 1.0, lyric: { poj: 'Bô', hanlo: '無' } },
          { id: 'u_v1_n20', pitch: 5, octave: 0, duration: 1.0, lyric: { poj: 'lâng', hanlo: '人' } },
          { id: 'u_v1_n21', pitch: 5, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'khòaⁿ', hanlo: '看' } },
          { id: 'u_v1_n22', pitch: 3, octave: 0, duration: 0.25, slurToNext: true, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v1_n23', pitch: 5, octave: 0, duration: 0.25, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v1_n24', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'kìⁿ', hanlo: '見' } },
        ],
      },
      {
        id: 'u_m6',
        measureNumber: 6,
        chord: 'Cm',
        isLineBreak: true,
        notes: [
          { id: 'u_v1_n25', pitch: 3, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'mî', hanlo: '暝' } },
          { id: 'u_v1_n26', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v1_n27', pitch: 3, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'ji̍t', hanlo: '日' } },
          { id: 'u_v1_n28', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v1_n29', pitch: 1, octave: 0, duration: 1.0, lyric: { poj: 'oàn', hanlo: '怨' } },
          { id: 'u_v1_n30', pitch: 6, octave: -1, duration: 1.0, lyric: { poj: 'chhè', hanlo: '嗟' } },
          { id: 'u_v1_b3', pitch: 'empty', octave: 0, duration: 0, lyric: { poj: '\n', hanlo: '\n', hanji: '\n', custom: '\n' } },
        ],
      },
      {
        id: 'u_m7',
        measureNumber: 7,
        chord: 'Gm',
        notes: [
          { id: 'u_v1_n31', pitch: 5, octave: -1, duration: 1.0, lyric: { poj: 'Hoe', hanlo: '花' } },
          { id: 'u_v1_n32', pitch: 6, octave: -1, duration: 1.0, lyric: { poj: 'siā', hanlo: '謝' } },
          { id: 'u_v1_n33', pitch: 5, octave: -1, duration: 1.0, lyric: { poj: 'lo̍h', hanlo: '落' } },
          { id: 'u_v1_n34', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'thô͘', hanlo: '土' } },
        ],
      },
      {
        id: 'u_m8',
        measureNumber: 8,
        chord: 'Bb',
        barlineType: 'double',
        isLineBreak: true,
        notes: [
          { id: 'u_v1_n35', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'put', hanlo: '不' } },
          { id: 'u_v1_n36', pitch: 2, octave: 0, duration: 1.0, lyric: { poj: 'chài', hanlo: '再' } },
          { id: 'u_v1_n37', pitch: 1, octave: 0, duration: 2.0, lyric: { poj: 'hôe', hanlo: '回' } },
          { id: 'u_v1_b4', pitch: 'empty', octave: 0, duration: 0, lyric: { poj: '\n', hanlo: '\n', hanji: '\n', custom: '\n' } },
        ],
      },

      // ======================================================================
      // VERSE 2 (Measures 9 - 16)
      // ======================================================================
      {
        id: 'u_m9',
        measureNumber: 9,
        chord: 'Bb',
        section: 'Verse 2',
        notes: [
          { id: 'u_v2_n1', pitch: 5, octave: -1, duration: 0.5, slurToNext: true, lyric: { poj: 'Hoe', hanlo: '花' } },
          { id: 'u_v2_n2', pitch: 6, octave: -1, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v2_n3', pitch: 5, octave: -1, duration: 1.0, lyric: { poj: 'lo̍h', hanlo: '落' } },
          { id: 'u_v2_n4', pitch: 3, octave: 0, duration: 2.0, lyric: { poj: 'thô͘', hanlo: '土' } },
        ],
      },
      {
        id: 'u_m10',
        measureNumber: 10,
        chord: 'Gm',
        isLineBreak: true,
        notes: [
          { id: 'u_v2_n5', pitch: 3, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'hoe', hanlo: '花' } },
          { id: 'u_v2_n6', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v2_n7', pitch: 1, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'lo̍h', hanlo: '落' } },
          { id: 'u_v2_n8', pitch: 6, octave: -1, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v2_n9', pitch: 5, octave: -1, duration: 2.0, lyric: { poj: 'thô͘', hanlo: '土' } },
          { id: 'u_v2_b1', pitch: 'empty', octave: 0, duration: 0, lyric: { poj: '\n', hanlo: '\n', hanji: '\n', custom: '\n' } },
        ],
      },
      {
        id: 'u_m11',
        measureNumber: 11,
        chord: 'Eb',
        notes: [
          { id: 'u_v2_n10', pitch: 1, octave: 0, duration: 0.5, lyric: { poj: 'ū', hanlo: '有' } },
          { id: 'u_v2_n11', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: 'siáⁿ', hanlo: '啥' } },
          { id: 'u_v2_n12', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'lâng', hanlo: '人' } },
          { id: 'u_v2_n13', pitch: 5, octave: 0, duration: 1.0, lyric: { poj: 'thang', hanlo: 'thang' } },
          { id: 'u_v2_n14', pitch: 1, octave: 1, duration: 0.5, slurToNext: true, annotation: '過門', lyric: { poj: '', hanlo: '' } },
          { id: 'u_v2_n15', pitch: 2, octave: 1, duration: 0.5, lyric: { poj: '', hanlo: '' } },
        ],
      },
      {
        id: 'u_m12',
        measureNumber: 12,
        chord: 'F7',
        isLineBreak: true,
        notes: [
          { id: 'u_v2_n16', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'khòaⁿ', hanlo: '看' } },
          { id: 'u_v2_n17', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'kò͘', hanlo: '顧' } },
          { id: 'u_v2_n18', pitch: 2, octave: 0, duration: 2.0, lyric: { poj: '', hanlo: '──' } },
          { id: 'u_v2_b2', pitch: 'empty', octave: 0, duration: 0, lyric: { poj: '\n', hanlo: '\n', hanji: '\n', custom: '\n' } },
        ],
      },
      {
        id: 'u_m13',
        measureNumber: 13,
        chord: 'Bb',
        notes: [
          { id: 'u_v2_n19', pitch: 5, octave: 0, duration: 1.0, lyric: { poj: 'Bô', hanlo: '無' } },
          { id: 'u_v2_n20', pitch: 5, octave: 0, duration: 1.0, lyric: { poj: 'chêng', hanlo: '情' } },
          { id: 'u_v2_n21', pitch: 5, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'hong', hanlo: '風' } },
          { id: 'u_v2_n22', pitch: 3, octave: 0, duration: 0.25, slurToNext: true, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v2_n23', pitch: 5, octave: 0, duration: 0.25, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v2_n24', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'hō͘', hanlo: '雨' } },
        ],
      },
      {
        id: 'u_m14',
        measureNumber: 14,
        chord: 'Cm',
        isLineBreak: true,
        notes: [
          { id: 'u_v2_n25', pitch: 3, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'gō͘', hanlo: '誤' } },
          { id: 'u_v2_n26', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v2_n27', pitch: 3, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'goán', hanlo: '阮' } },
          { id: 'u_v2_n28', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v2_n29', pitch: 1, octave: 0, duration: 1.0, lyric: { poj: 'chiân', hanlo: '前' } },
          { id: 'u_v2_n30', pitch: 6, octave: -1, duration: 1.0, lyric: { poj: 'tô͘', hanlo: '途' } },
          { id: 'u_v2_b3', pitch: 'empty', octave: 0, duration: 0, lyric: { poj: '\n', hanlo: '\n', hanji: '\n', custom: '\n' } },
        ],
      },
      {
        id: 'u_m15',
        measureNumber: 15,
        chord: 'Gm',
        notes: [
          { id: 'u_v2_n31', pitch: 5, octave: -1, duration: 1.0, lyric: { poj: 'hoe', hanlo: '花' } },
          { id: 'u_v2_n32', pitch: 6, octave: -1, duration: 1.0, lyric: { poj: 'lúi', hanlo: '蕊' } },
          { id: 'u_v2_n33', pitch: 5, octave: -1, duration: 1.0, lyric: { poj: 'tiau', hanlo: '凋' } },
          { id: 'u_v2_n34', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'lo̍h', hanlo: '落' } },
        ],
      },
      {
        id: 'u_m16',
        measureNumber: 16,
        chord: 'Bb',
        barlineType: 'double',
        isLineBreak: true,
        notes: [
          { id: 'u_v2_n35', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'beh', hanlo: 'beh' } },
          { id: 'u_v2_n36', pitch: 2, octave: 0, duration: 1.0, lyric: { poj: 'jû', hanlo: '如' } },
          { id: 'u_v2_n37', pitch: 1, octave: 0, duration: 2.0, lyric: { poj: 'hô', hanlo: '何' } },
          { id: 'u_v2_b4', pitch: 'empty', octave: 0, duration: 0, lyric: { poj: '\n', hanlo: '\n', hanji: '\n', custom: '\n' } },
        ],
      },

      // ======================================================================
      // VERSE 3 (Measures 17 - 24)
      // ======================================================================
      {
        id: 'u_m17',
        measureNumber: 17,
        chord: 'Bb',
        section: 'Verse 3',
        notes: [
          { id: 'u_v3_n1', pitch: 5, octave: -1, duration: 0.5, slurToNext: true, lyric: { poj: 'Ú', hanlo: '雨' } },
          { id: 'u_v3_n2', pitch: 6, octave: -1, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v3_n3', pitch: 5, octave: -1, duration: 1.0, lyric: { poj: 'bô', hanlo: '無' } },
          { id: 'u_v3_n4', pitch: 3, octave: 0, duration: 2.0, lyric: { poj: 'chêng', hanlo: '情' } },
        ],
      },
      {
        id: 'u_m18',
        measureNumber: 18,
        chord: 'Gm',
        isLineBreak: true,
        notes: [
          { id: 'u_v3_n5', pitch: 3, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'ú', hanlo: '雨' } },
          { id: 'u_v3_n6', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v3_n7', pitch: 1, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'bô', hanlo: '無' } },
          { id: 'u_v3_n8', pitch: 6, octave: -1, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v3_n9', pitch: 5, octave: -1, duration: 2.0, lyric: { poj: 'chêng', hanlo: '情' } },
          { id: 'u_v3_b1', pitch: 'empty', octave: 0, duration: 0, lyric: { poj: '\n', hanlo: '\n', hanji: '\n', custom: '\n' } },
        ],
      },
      {
        id: 'u_m19',
        measureNumber: 19,
        chord: 'Eb',
        notes: [
          { id: 'u_v3_n10', pitch: 1, octave: 0, duration: 0.5, lyric: { poj: 'bô', hanlo: '無' } },
          { id: 'u_v3_n11', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: 'siūⁿ', hanlo: '想' } },
          { id: 'u_v3_n12', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'gún', hanlo: '阮' } },
          { id: 'u_v3_n13', pitch: 5, octave: 0, duration: 1.0, lyric: { poj: 'ê', hanlo: 'ê' } },
          { id: 'u_v3_n14', pitch: 1, octave: 1, duration: 0.5, slurToNext: true, annotation: '過門', lyric: { poj: '', hanlo: '' } },
          { id: 'u_v3_n15', pitch: 2, octave: 1, duration: 0.5, lyric: { poj: '', hanlo: '' } },
        ],
      },
      {
        id: 'u_m20',
        measureNumber: 20,
        chord: 'F7',
        isLineBreak: true,
        notes: [
          { id: 'u_v3_n16', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'chiân', hanlo: '前' } },
          { id: 'u_v3_n17', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'tô͘', hanlo: '途' } },
          { id: 'u_v3_n18', pitch: 2, octave: 0, duration: 2.0, lyric: { poj: '', hanlo: '──' } },
          { id: 'u_v3_b2', pitch: 'empty', octave: 0, duration: 0, lyric: { poj: '\n', hanlo: '\n', hanji: '\n', custom: '\n' } },
        ],
      },
      {
        id: 'u_m21',
        measureNumber: 21,
        chord: 'Bb',
        notes: [
          { id: 'u_v3_n19', pitch: 5, octave: 0, duration: 1.0, lyric: { poj: 'Pēng', hanlo: '並' } },
          { id: 'u_v3_n20', pitch: 5, octave: 0, duration: 1.0, lyric: { poj: 'bô', hanlo: '無' } },
          { id: 'u_v3_n21', pitch: 5, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'khòaⁿ', hanlo: '看' } },
          { id: 'u_v3_n22', pitch: 3, octave: 0, duration: 0.25, slurToNext: true, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v3_n23', pitch: 5, octave: 0, duration: 0.25, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v3_n24', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'hō͘', hanlo: '護' } },
        ],
      },
      {
        id: 'u_m22',
        measureNumber: 22,
        chord: 'Cm',
        isLineBreak: true,
        notes: [
          { id: 'u_v3_n25', pitch: 3, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'nńg', hanlo: '軟' } },
          { id: 'u_v3_n26', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v3_n27', pitch: 3, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'jio̍k', hanlo: '弱' } },
          { id: 'u_v3_n28', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v3_n29', pitch: 1, octave: 0, duration: 1.0, lyric: { poj: 'sim', hanlo: '心' } },
          { id: 'u_v3_n30', pitch: 6, octave: -1, duration: 1.0, lyric: { poj: 'sèng', hanlo: '性' } },
          { id: 'u_v3_b3', pitch: 'empty', octave: 0, duration: 0, lyric: { poj: '\n', hanlo: '\n', hanji: '\n', custom: '\n' } },
        ],
      },
      {
        id: 'u_m23',
        measureNumber: 23,
        chord: 'Gm',
        notes: [
          { id: 'u_v3_n31', pitch: 5, octave: -1, duration: 1.0, lyric: { poj: 'Hō͘', hanlo: 'Hō͘' } },
          { id: 'u_v3_n32', pitch: 6, octave: -1, duration: 1.0, lyric: { poj: 'gún', hanlo: '阮' } },
          { id: 'u_v3_n33', pitch: 5, octave: -1, duration: 1.0, lyric: { poj: 'chiân', hanlo: '前' } },
          { id: 'u_v3_n34', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'tô͘', hanlo: '途' } },
        ],
      },
      {
        id: 'u_m24',
        measureNumber: 24,
        chord: 'Bb',
        barlineType: 'double',
        isLineBreak: true,
        notes: [
          { id: 'u_v3_n35', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'sit', hanlo: '失' } },
          { id: 'u_v3_n36', pitch: 2, octave: 0, duration: 1.0, lyric: { poj: 'kong', hanlo: '光' } },
          { id: 'u_v3_n37', pitch: 1, octave: 0, duration: 2.0, lyric: { poj: 'bêng', hanlo: '明' } },
          { id: 'u_v3_b4', pitch: 'empty', octave: 0, duration: 0, lyric: { poj: '\n', hanlo: '\n', hanji: '\n', custom: '\n' } },
        ],
      },

      // ======================================================================
      // VERSE 4 (Measures 25 - 32)
      // ======================================================================
      {
        id: 'u_m25',
        measureNumber: 25,
        chord: 'Bb',
        section: 'Verse 4',
        notes: [
          { id: 'u_v4_n1', pitch: 5, octave: -1, duration: 0.5, slurToNext: true, lyric: { poj: 'Ú', hanlo: '雨' } },
          { id: 'u_v4_n2', pitch: 6, octave: -1, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v4_n3', pitch: 5, octave: -1, duration: 1.0, lyric: { poj: 'chúi', hanlo: '水' } },
          { id: 'u_v4_n4', pitch: 3, octave: 0, duration: 2.0, lyric: { poj: 'tih', hanlo: '滴' } },
        ],
      },
      {
        id: 'u_m26',
        measureNumber: 26,
        chord: 'Gm',
        isLineBreak: true,
        notes: [
          { id: 'u_v4_n5', pitch: 3, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'ú', hanlo: '雨' } },
          { id: 'u_v4_n6', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v4_n7', pitch: 1, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'chúi', hanlo: '水' } },
          { id: 'u_v4_n8', pitch: 6, octave: -1, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v4_n9', pitch: 5, octave: -1, duration: 2.0, lyric: { poj: 'tih', hanlo: '滴' } },
          { id: 'u_v4_b1', pitch: 'empty', octave: 0, duration: 0, lyric: { poj: '\n', hanlo: '\n', hanji: '\n', custom: '\n' } },
        ],
      },
      {
        id: 'u_m27',
        measureNumber: 27,
        chord: 'Eb',
        notes: [
          { id: 'u_v4_n10', pitch: 1, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'ín', hanlo: '引' } },
          { id: 'u_v4_n11', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v4_n12', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'gún', hanlo: '阮' } },
          { id: 'u_v4_n13', pitch: 5, octave: 0, duration: 1.0, lyric: { poj: 'ji̍p', hanlo: '入' } },
          { id: 'u_v4_n14', pitch: 1, octave: 1, duration: 0.5, slurToNext: true, annotation: '過門', lyric: { poj: '', hanlo: '' } },
          { id: 'u_v4_n15', pitch: 2, octave: 1, duration: 0.5, lyric: { poj: '', hanlo: '' } },
        ],
      },
      {
        id: 'u_m28',
        measureNumber: 28,
        chord: 'F7',
        isLineBreak: true,
        notes: [
          { id: 'u_v4_n16', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'siū', hanlo: '受' } },
          { id: 'u_v4_n17', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'lān', hanlo: '難' } },
          { id: 'u_v4_n18', pitch: 2, octave: 0, duration: 2.0, lyric: { poj: 'tî', hanlo: '池' } },
          { id: 'u_v4_b2', pitch: 'empty', octave: 0, duration: 0, lyric: { poj: '\n', hanlo: '\n', hanji: '\n', custom: '\n' } },
        ],
      },
      {
        id: 'u_m29',
        measureNumber: 29,
        chord: 'Bb',
        notes: [
          { id: 'u_v4_n19', pitch: 5, octave: 0, duration: 1.0, lyric: { poj: 'Chóaⁿ', hanlo: '怎' } },
          { id: 'u_v4_n20', pitch: 5, octave: 0, duration: 1.0, lyric: { poj: 'iūⁿ', hanlo: '樣' } },
          { id: 'u_v4_n21', pitch: 5, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'hō͘', hanlo: 'hō͘' } },
          { id: 'u_v4_n22', pitch: 3, octave: 0, duration: 0.25, slurToNext: true, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v4_n23', pitch: 5, octave: 0, duration: 0.25, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v4_n24', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'gún', hanlo: '阮' } },
        ],
      },
      {
        id: 'u_m30',
        measureNumber: 30,
        chord: 'Cm',
        isLineBreak: true,
        notes: [
          { id: 'u_v4_n25', pitch: 3, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'lī', hanlo: '離' } },
          { id: 'u_v4_n26', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v4_n27', pitch: 3, octave: 0, duration: 0.5, slurToNext: true, lyric: { poj: 'hio̍h', hanlo: '葉' } },
          { id: 'u_v4_n28', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: '', hanlo: '' } },
          { id: 'u_v4_n29', pitch: 1, octave: 0, duration: 1.0, lyric: { poj: 'lī', hanlo: '離' } },
          { id: 'u_v4_n30', pitch: 6, octave: -1, duration: 1.0, lyric: { poj: 'ki', hanlo: '枝' } },
          { id: 'u_v4_b3', pitch: 'empty', octave: 0, duration: 0, lyric: { poj: '\n', hanlo: '\n', hanji: '\n', custom: '\n' } },
        ],
      },
      {
        id: 'u_m31',
        measureNumber: 31,
        chord: 'Gm',
        notes: [
          { id: 'u_v4_n31', pitch: 5, octave: -1, duration: 1.0, lyric: { poj: 'Éng', hanlo: '永' } },
          { id: 'u_v4_n32', pitch: 6, octave: -1, duration: 1.0, lyric: { poj: 'oán', hanlo: '遠' } },
          { id: 'u_v4_n33', pitch: 5, octave: -1, duration: 1.0, lyric: { poj: 'bô', hanlo: '無' } },
          { id: 'u_v4_n34', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'lâng', hanlo: '人' } },
        ],
      },
      {
        id: 'u_m32',
        measureNumber: 32,
        chord: 'Bb',
        barlineType: 'end',
        isLineBreak: true,
        notes: [
          { id: 'u_v4_n35', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'thang', hanlo: 'thang' } },
          { id: 'u_v4_n36', pitch: 2, octave: 0, duration: 1.0, lyric: { poj: 'khòaⁿ', hanlo: '看' } },
          { id: 'u_v4_n37', pitch: 1, octave: 0, duration: 2.0, lyric: { poj: 'kìⁿ', hanlo: '見' } },
          { id: 'u_v4_b4', pitch: 'empty', octave: 0, duration: 0, lyric: { poj: '\n', hanlo: '\n', hanji: '\n', custom: '\n' } },
        ],
      },
    ],
  },
  {
    id: 'i-si-lan-e-po-poe',
    title: '伊是咱的寶貝 (I sī Lán ê Pó-pòe)',
    subtitle: '陳明章 詞曲 / 1993 經典臺灣歌謠 (完整白話字 POJ 對齊)',
    composer: '陳明章 (Tân Bêng-chiong)',
    lyricist: '陳明章 (Tân Bêng-chiong)',
    key: 'F',
    timeSignature: '4/4',
    bpm: 72,
    notesPerLine: 4,
    description: '經典臺灣民謠《伊是咱的寶貝》，F調 (4/4拍)，五線譜/簡譜標準數位化轉換，完整收錄白話字 (POJ) 與漢羅字對齊之全曲（16小節），短句分段好讀好唱。',
    measures: [
      {
        id: 'i_m1',
        measureNumber: 1,
        chord: 'F',
        section: '主歌 1-A',
        notes: [
          { id: 'i_n1_1', pitch: 5, octave: 0, duration: 1.5, isDotted: true, slurToNext: true, lyric: { poj: 'Chit', hanlo: '一' } },
          { id: 'i_n1_2', pitch: 6, octave: 0, duration: 0.5, lyric: { poj: 'lúi', hanlo: '蕊' } },
          { id: 'i_n1_3', pitch: 3, octave: 0, duration: 2.0, lyric: { poj: 'hoe', hanlo: '花' } },
        ],
      },
      {
        id: 'i_m2',
        measureNumber: 2,
        chord: 'C',
        isLineBreak: true,
        notes: [
          { id: 'i_n2_1', pitch: 2, octave: 0, duration: 1.5, isDotted: true, slurToNext: true, lyric: { poj: 'sìⁿ', hanlo: '生' } },
          { id: 'i_n2_2', pitch: 3, octave: 0, duration: 0.5, lyric: { poj: 'lo̍h', hanlo: '落' } },
          { id: 'i_n2_3', pitch: 2, octave: 0, duration: 2.0, lyric: { poj: 'tē,\n', hanlo: '地，\n' } },
        ],
      },
      {
        id: 'i_m3',
        measureNumber: 3,
        chord: 'C7',
        notes: [
          { id: 'i_n3_1', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: 'Pa', hanlo: '爸' } },
          { id: 'i_n3_2', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: 'pa', hanlo: '爸' } },
          { id: 'i_n3_3', pitch: 5, octave: 0, duration: 0.5, lyric: { poj: 'ma', hanlo: '媽' } },
          { id: 'i_n3_4', pitch: 6, octave: 0, duration: 0.5, lyric: { poj: 'ma', hanlo: '媽' } },
          { id: 'i_n3_5', pitch: 5, octave: 0, duration: 1.0, lyric: { poj: 'thiàⁿ', hanlo: '疼' } },
          { id: 'i_n3_6', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'siāng', hanlo: '上' } },
        ],
      },
      {
        id: 'i_m4',
        measureNumber: 4,
        chord: 'F',
        isLineBreak: true,
        notes: [
          { id: 'i_n4_1', pitch: 1, octave: 0, duration: 4.0, lyric: { poj: 'chē,\n', hanlo: '多，\n' } },
        ],
      },
      {
        id: 'i_m5',
        measureNumber: 5,
        chord: 'F',
        section: '主歌 1-B',
        notes: [
          { id: 'i_n5_1', pitch: 5, octave: 0, duration: 1.5, isDotted: true, slurToNext: true, lyric: { poj: 'Hong', hanlo: '風' } },
          { id: 'i_n5_2', pitch: 6, octave: 0, duration: 0.5, lyric: { poj: 'nā', hanlo: '若' } },
          { id: 'i_n5_3', pitch: 3, octave: 0, duration: 2.0, lyric: { poj: 'chhoe', hanlo: '吹' } },
        ],
      },
      {
        id: 'i_m6',
        measureNumber: 6,
        chord: 'C',
        isLineBreak: true,
        notes: [
          { id: 'i_n6_1', pitch: 2, octave: 0, duration: 1.5, isDotted: true, slurToNext: true, lyric: { poj: 'ài', hanlo: '愛' } },
          { id: 'i_n6_2', pitch: 3, octave: 0, duration: 0.5, lyric: { poj: 'kah', hanlo: '甲' } },
          { id: 'i_n6_3', pitch: 2, octave: 0, duration: 2.0, lyric: { poj: 'phōe,\n', hanlo: '被，\n' } },
        ],
      },
      {
        id: 'i_m7',
        measureNumber: 7,
        chord: 'Bb',
        notes: [
          { id: 'i_n7_1', pitch: 3, octave: 0, duration: 0.5, lyric: { poj: 'M̄', hanlo: '唔' } },
          { id: 'i_n7_2', pitch: 5, octave: 0, duration: 0.5, lyric: { poj: 'thang', hanlo: '通' } },
          { id: 'i_n7_3', pitch: 6, octave: 0, duration: 0.5, lyric: { poj: 'hō͘', hanlo: '互' } },
          { id: 'i_n7_4', pitch: 5, octave: 0, duration: 0.5, lyric: { poj: 'i', hanlo: '伊' } },
          { id: 'i_n7_5', pitch: 3, octave: 0, duration: 0.5, lyric: { poj: 'tūi', hanlo: '墜' } },
          { id: 'i_n7_6', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: 'lo̍h', hanlo: '落' } },
          { id: 'i_n7_7', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: 'o͘', hanlo: '黑' } },
          { id: 'i_n7_8', pitch: 3, octave: 0, duration: 0.5, lyric: { poj: 'àm', hanlo: '暗' } },
        ],
      },
      {
        id: 'i_m8',
        measureNumber: 8,
        chord: 'F',
        isLineBreak: true,
        notes: [
          { id: 'i_n8_1', pitch: 1, octave: 0, duration: 4.0, lyric: { poj: 'tē;\n', hanlo: '地，\n' } },
        ],
      },
      {
        id: 'i_m9',
        measureNumber: 9,
        chord: 'F',
        section: '副歌 2-A',
        notes: [
          { id: 'i_n9_1', pitch: 1, octave: 0, duration: 0.5, lyric: { poj: 'Beh', hanlo: '欲' } },
          { id: 'i_n9_2', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: 'khui', hanlo: '開' } },
          { id: 'i_n9_3', pitch: 3, octave: 0, duration: 0.5, lyric: { poj: 'ê', hanlo: '的' } },
          { id: 'i_n9_4', pitch: 5, octave: 0, duration: 0.5, lyric: { poj: 'hoe', hanlo: '花' } },
          { id: 'i_n9_5', pitch: 3, octave: 0, duration: 0.5, lyric: { poj: 'su', hanlo: '需' } },
          { id: 'i_n9_6', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: 'iàu', hanlo: '要' } },
          { id: 'i_n9_7', pitch: 1, octave: 0, duration: 0.5, lyric: { poj: 'lí', hanlo: '你' } },
          { id: 'i_n9_8', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: 'góa', hanlo: '我' } },
        ],
      },
      {
        id: 'i_m10',
        measureNumber: 10,
        chord: 'C',
        isLineBreak: true,
        notes: [
          { id: 'i_n10_1', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'ê', hanlo: '的' } },
          { id: 'i_n10_2', pitch: 1, octave: 0, duration: 1.0, lyric: { poj: 'koan', hanlo: '關' } },
          { id: 'i_n10_3', pitch: 2, octave: 0, duration: 2.0, lyric: { poj: 'sim,\n', hanlo: '心，\n' } },
        ],
      },
      {
        id: 'i_m11',
        measureNumber: 11,
        chord: 'Bb',
        notes: [
          { id: 'i_n11_1', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: 'Hō͘', hanlo: '互' } },
          { id: 'i_n11_2', pitch: 3, octave: 0, duration: 0.5, lyric: { poj: 'i', hanlo: '伊' } },
          { id: 'i_n11_3', pitch: 5, octave: 0, duration: 0.5, lyric: { poj: 'chit', hanlo: '一' } },
          { id: 'i_n11_4', pitch: 6, octave: 0, duration: 0.5, lyric: { poj: 'phìⁿ', hanlo: '片' } },
          { id: 'i_n11_5', pitch: 5, octave: 0, duration: 0.5, lyric: { poj: 'seng', hanlo: '生' } },
          { id: 'i_n11_6', pitch: 3, octave: 0, duration: 0.5, lyric: { poj: 'tióng', hanlo: '長' } },
          { id: 'i_n11_7', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: 'ê', hanlo: '的' } },
          { id: 'i_n11_8', pitch: 3, octave: 0, duration: 0.5, lyric: { poj: 'thó', hanlo: '土' } },
        ],
      },
      {
        id: 'i_m12',
        measureNumber: 12,
        chord: 'F',
        isLineBreak: true,
        notes: [
          { id: 'i_n12_1', pitch: 1, octave: 0, duration: 4.0, lyric: { poj: 'tē,\n', hanlo: '地，\n' } },
        ],
      },
      {
        id: 'i_m13',
        measureNumber: 13,
        chord: 'F',
        section: '副歌 2-B',
        notes: [
          { id: 'i_n13_1', pitch: 1, octave: 0, duration: 0.5, lyric: { poj: 'Chhiú', hanlo: '手' } },
          { id: 'i_n13_2', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: 'khan', hanlo: '牽' } },
          { id: 'i_n13_3', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'chhiú', hanlo: '手' } },
          { id: 'i_n13_4', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: 'sim', hanlo: '心' } },
          { id: 'i_n13_5', pitch: 3, octave: 0, duration: 0.5, lyric: { poj: 'liân', hanlo: '連' } },
          { id: 'i_n13_6', pitch: 5, octave: 0, duration: 1.0, lyric: { poj: 'sim', hanlo: '心' } },
        ],
      },
      {
        id: 'i_m14',
        measureNumber: 14,
        chord: 'Dm',
        isLineBreak: true,
        notes: [
          { id: 'i_n14_1', pitch: 6, octave: 0, duration: 1.0, lyric: { poj: 'lán', hanlo: '咱' } },
          { id: 'i_n14_2', pitch: 5, octave: 0, duration: 1.0, lyric: { poj: 'khiā', hanlo: '站' } },
          { id: 'i_n14_3', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: 'chò', hanlo: '作' } },
          { id: 'i_n14_4', pitch: 2, octave: 0, duration: 0.5, lyric: { poj: 'hóe,\n', hanlo: '伙，\n' } },
          { id: 'i_n14_5', pitch: 0, octave: 0, duration: 1.0, lyric: {} },
        ],
      },
      {
        id: 'i_m15',
        measureNumber: 15,
        chord: 'Bb',
        notes: [
          { id: 'i_n15_1', pitch: 2, octave: 0, duration: 1.0, lyric: { poj: 'I', hanlo: '伊' } },
          { id: 'i_n15_2', pitch: 3, octave: 0, duration: 1.0, lyric: { poj: 'sī', hanlo: '是' } },
          { id: 'i_n15_3', pitch: 5, octave: 0, duration: 1.0, lyric: { poj: 'lán', hanlo: '咱' } },
          { id: 'i_n15_4', pitch: 6, octave: 0, duration: 1.0, lyric: { poj: 'ê', hanlo: '的' } },
        ],
      },
      {
        id: 'i_m16',
        measureNumber: 16,
        chord: 'F',
        barlineType: 'end',
        isLineBreak: true,
        notes: [
          { id: 'i_n16_1', pitch: 5, octave: 0, duration: 2.0, slurToNext: true, lyric: { poj: 'pó', hanlo: '寶' } },
          { id: 'i_n16_2', pitch: 1, octave: 0, duration: 2.0, lyric: { poj: 'pòe.\n', hanlo: '貝。\n' } },
        ],
      },
    ],
  },
];

/**
 * Creates a brand-new empty/fresh song template ready for editing.
 */
export function createFreshSong(title = '未命名樂曲'): Song {
  const timestamp = Date.now();
  return {
    id: `song-${timestamp}`,
    title,
    subtitle: '',
    composer: '',
    lyricist: '',
    key: 'C',
    timeSignature: '4/4',
    bpm: 80,
    notesPerLine: 4,
    description: '',
    measures: [
      {
        id: `m-${timestamp}-1`,
        measureNumber: 1,
        chord: 'C',
        section: 'Verse 1',
        notes: [
          { id: `n-${timestamp}-1`, pitch: 1, octave: 0, duration: 1, lyric: { poj: '', hanlo: '' } },
          { id: `n-${timestamp}-2`, pitch: 2, octave: 0, duration: 1, lyric: { poj: '', hanlo: '' } },
          { id: `n-${timestamp}-3`, pitch: 3, octave: 0, duration: 1, lyric: { poj: '', hanlo: '' } },
          { id: `n-${timestamp}-4`, pitch: 5, octave: 0, duration: 1, lyric: { poj: '', hanlo: '' } },
        ],
      },
    ],
  };
}
